# Generated by Django 6.0.7 on 2026-08-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='receber_notificacoes',
        ),
    ]
