# Generated by Django 6.0.7 on 2026-09-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0003_remove_doador_receber_notificacoes'),
        ('hemocentros', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(help_text='Ex: 09:30', max_length=5)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='confirmado', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='doadores.doador')),
                ('hemocentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='hemocentros.hemocentro')),
            ],
            options={
                'verbose_name': 'Agendamento de doação',
                'verbose_name_plural': 'Agendamentos de doação',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
