# Generated by Django 6.0.7 on 2026-08-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoHemocentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='hemocentros/')),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto do hemocentro',
                'verbose_name_plural': 'Fotos do hemocentro',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('descricao', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('horario_funcionamento', models.TextField(help_text='Ex: Segunda a sexta: 08h às 17h')),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('aprovado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hemocentro',
                'verbose_name_plural': 'Hemocentros',
                'ordering': ['nome'],
            },
        ),
    ]
