# Generated by Django 6.0.7 on 2026-08-03 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hemocentros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hemocentro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotohemocentro',
            name='hemocentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='hemocentros.hemocentro'),
        ),
    ]
