# Generated by Django 6.0.7 on 2026-08-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hemocentros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessidadeSanguinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('nivel_urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('quantidade_bolsas', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('notificacao_enviada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hemocentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='hemocentros.hemocentro')),
            ],
            options={
                'verbose_name': 'Necessidade de sangue',
                'verbose_name_plural': 'Necessidades de sangue',
                'ordering': ['-criado_em'],
            },
        ),
    ]
