# Generated by Django 6.0.7 on 2026-08-04 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0003_remove_doador_receber_notificacoes'),
        ('necessidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoDoador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='doadores.doador')),
                ('necessidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_doadores', to='necessidades.necessidadesanguinea')),
            ],
            options={
                'verbose_name': 'Notificação de doador',
                'verbose_name_plural': 'Notificações de doadores',
                'ordering': ['-criado_em'],
            },
        ),
    ]
